function lgraph =  modifyConvLayers(neural,means,offset)
    switch class(neural)
      case 'SeriesNetwork'
        lgraph = layerGraph(neural.Layers);
      case 'DAGNetwork'
        lgraph = layerGraph(neural);
    end
    inlayers = lgraph.Layers;
    l_kernel = findconv(inlayers);
    l_length = length(l_kernel);

    for l = 1:l_length
        oldlayer = inlayers(l_kernel(l));
        switch class(oldlayer)
          case 'nnet.cnn.layer.GroupedConvolution2DLayer'
            newlayer = groupedConvolution2dLayerCustom(oldlayer.FilterSize,oldlayer.NumFiltersPerGroup,oldlayer.NumGroups,...
                                                'Name',oldlayer.Name,...
                                                'Stride',oldlayer.Stride,...
                                                'DilationFactor',oldlayer.DilationFactor,...
                                                'Padding',oldlayer.PaddingSize,...
                                                'Weights',oldlayer.Weights,...
                                                'Bias',oldlayer.Bias + offset{l},...
                                                'WeightLearnRateFactor',oldlayer.WeightLearnRateFactor,...
                                                'BiasLearnRateFactor',oldlayer.BiasLearnRateFactor,...
                                                'WeightL2Factor',oldlayer.WeightL2Factor,...
                                                'BiasL2Factor',oldlayer.BiasL2Factor,...
                                                'WeightsInitializer',oldlayer.WeightsInitializer,...
                                                'BiasInitializer',oldlayer.BiasInitializer,...
                                                'ChannelMean',means{l});
          case 'nnet.cnn.layer.Convolution2DLayer'
            newlayer = convolution2dLayerCustom(oldlayer.FilterSize,oldlayer.NumFilters,...
                                                'Name',oldlayer.Name,...
                                                'NumChannels',oldlayer.NumChannels,...
                                                'Stride',oldlayer.Stride,...
                                                'DilationFactor',oldlayer.DilationFactor,...
                                                'Padding',oldlayer.PaddingSize,...
                                                'Weights',oldlayer.Weights,...
                                                'Bias',oldlayer.Bias + offset{l},...
                                                'WeightLearnRateFactor',oldlayer.WeightLearnRateFactor,...
                                                'BiasLearnRateFactor',oldlayer.BiasLearnRateFactor,...
                                                'WeightL2Factor',oldlayer.WeightL2Factor,...
                                                'BiasL2Factor',oldlayer.BiasL2Factor,...
                                                'WeightsInitializer',oldlayer.WeightsInitializer,...
                                                'BiasInitializer',oldlayer.BiasInitializer,...
                                                'ChannelMean',means{l});
          case 'nnet.cnn.layer.FullyConnectedLayer'
            newlayer = fullyConnectedLayerCustom(oldlayer.OutputSize,...
                                                'Name',oldlayer.Name,...
                                                'Weights',oldlayer.Weights,...
                                                'Bias',oldlayer.Bias + offset{l},...
                                                'WeightLearnRateFactor',oldlayer.WeightLearnRateFactor,...
                                                'BiasLearnRateFactor',oldlayer.BiasLearnRateFactor,...
                                                'WeightL2Factor',oldlayer.WeightL2Factor,...
                                                'BiasL2Factor',oldlayer.BiasL2Factor,...
                                                'WeightsInitializer',oldlayer.WeightsInitializer,...
                                                'BiasInitializer',oldlayer.BiasInitializer,...
                                                'ChannelMean',means{l});
        end
        lgraph = replaceLayer(lgraph,oldlayer.Name,newlayer);
    end
end
